main: jdz.bukkitUtils.JonosBukkitUtils
name: JBU
version: 0.11
author: Jonodonozym
description: Bunch of utilities to fast-track plugin development
softdepend: [Vault, WorldEdit]

commands:
  reloadConfig:
    alias: rc
  saveConfig:
    alias: sc