main: jdz.bukkitUtils.JonosBukkitUtils
name: JBU
version: 1.0
author: Jonodonozym
description: Bunch of utilities to fast-track plugin development
softdepend: [Vault, WorldEdit]
api-version: 1.13

commands:
  reloadConfig:
    alias: rc
  saveConfig:
    alias: sc